# Generated by Django 2.2.1 on 2019-05-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigoRegCalificado', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nombrePrograma', models.CharField(max_length=30)),
                ('duracion', models.IntegerField()),
                ('perfil', models.CharField(max_length=30)),
                ('estadoActual', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('contrasena', models.CharField(max_length=20)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Programa')),
            ],
        ),
    ]
