# Generated by Django 2.2.1 on 2019-05-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_remove_administrador_programa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='nombrePrograma',
            field=models.CharField(max_length=50),
        ),
    ]
