# Generated by Django 2.2.1 on 2019-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('identificacion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombreevento', models.CharField(db_column='nombreEvento', max_length=20)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('evento_identificacion', models.CharField(db_column='Evento_identificacion', max_length=30)),
            ],
            options={
                'db_table': 'Organizador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigoregcalificado', models.CharField(db_column='codigoRegCalificado', max_length=40, primary_key=True, serialize=False)),
                ('nombreprograma', models.CharField(db_column='nombrePrograma', max_length=30)),
                ('duracion', models.IntegerField()),
                ('perfil', models.CharField(max_length=30)),
                ('estadoactual', models.SmallIntegerField(db_column='estadoActual')),
            ],
            options={
                'db_table': 'Programa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Tipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('contrasena', models.CharField(max_length=20)),
                ('usuario_identificacion', models.IntegerField(db_column='Usuario_identificacion')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioEvento',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_identificacion', models.IntegerField(db_column='Usuario_identificacion')),
                ('evento_identificacion', models.CharField(db_column='Evento_identificacion', max_length=30)),
            ],
            options={
                'db_table': 'Usuario_Evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioPrograma',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_identificacion', models.IntegerField(db_column='Usuario_identificacion')),
                ('programa_codigoregcalificado', models.CharField(db_column='Programa_codigoRegCalificado', max_length=40)),
            ],
            options={
                'db_table': 'Usuario_Programa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioTipo',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_identificacion', models.IntegerField(db_column='Tipo_identificacion')),
                ('usuario_identificacion', models.IntegerField(db_column='Usuario_identificacion')),
            ],
            options={
                'db_table': 'Usuario_Tipo',
                'managed': True,
            },
        ),
    ]
