# Generated by Django 2.2.1 on 2019-05-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liderAutoevaluacion', '0001_initial'),
        ('administrador', '0001_initial'),
        ('egresados', '0002_auto_20190524_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('contrasena', models.CharField(max_length=20)),
                ('evento', models.ManyToManyField(to='liderAutoevaluacion.Evento')),
                ('programa', models.ManyToManyField(to='administrador.Programa')),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Organizador',
        ),
        migrations.DeleteModel(
            name='Programa',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='UsuarioEvento',
        ),
        migrations.DeleteModel(
            name='UsuarioPrograma',
        ),
        migrations.DeleteModel(
            name='UsuarioTipo',
        ),
    ]
