# Generated by Django 2.2.1 on 2019-05-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('identificacion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombreEvento', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liderAutoevaluacion.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='LiderAutoevaluacion',
            fields=[
                ('identificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('contrasena', models.CharField(max_length=20)),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Programa')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='liderAutoevaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liderAutoevaluacion.LiderAutoevaluacion'),
        ),
    ]
